import '../models/category_model.dart';

class CategoryConstants {
  static const List<CategoryModel> defaultCategories = [
    CategoryModel(
      categoryId: 'meals_entertainment',
      name: 'Meals & Entertainment',
      icon: '🍽️',
      color: '#FF6B6B',
      keywords: [
        'coffee',
        'lunch',
        'restaurant',
        'cafe',
        'food',
        'dinner',
        'breakfast',
        'meal',
        'takeaway',
        'steers',
        'mcdonalds',
        'kfc',
        'nandos',
      ],
      isDefault: true,
      taxDeductibleByDefault: true,
    ),
    CategoryModel(
      categoryId: 'travel_transport',
      name: 'Travel & Transport',
      icon: '🚗',
      color: '#4ECDC4',
      keywords: [
        'uber',
        'bolt',
        'taxi',
        'fuel',
        'petrol',
        'flight',
        'bus',
        'train',
        'parking',
        'toll',
        'gautrain',
      ],
      isDefault: true,
      taxDeductibleByDefault: true,
    ),
    CategoryModel(
      categoryId: 'office_supplies',
      name: 'Office Supplies',
      icon: '📎',
      color: '#45B7D1',
      keywords: [
        'stationery',
        'ink',
        'paper',
        'printer',
        'pens',
        'notebook',
        'folders',
        'envelopes',
      ],
      isDefault: true,
      taxDeductibleByDefault: true,
    ),
    CategoryModel(
      categoryId: 'software_subscriptions',
      name: 'Software & Subscriptions',
      icon: '💻',
      color: '#96CEB4',
      keywords: [
        'aws',
        'github',
        'figma',
        'slack',
        'notion',
        'zoom',
        'netflix',
        'adobe',
        'microsoft',
        'google',
        'dropbox',
        'linear',
        'vercel',
      ],
      isDefault: true,
      taxDeductibleByDefault: true,
    ),
    CategoryModel(
      categoryId: 'utilities',
      name: 'Utilities',
      icon: '⚡',
      color: '#FFEAA7',
      keywords: [
        'electricity',
        'water',
        'internet',
        'eskom',
        'telkom',
        'vodacom',
        'mtn',
        'cell c',
        'rain',
        'afrihost',
        'fibre',
      ],
      isDefault: true,
      taxDeductibleByDefault: true,
    ),
    CategoryModel(
      categoryId: 'medical',
      name: 'Medical',
      icon: '🏥',
      color: '#DDA0DD',
      keywords: [
        'pharmacy',
        'doctor',
        'clinic',
        'hospital',
        'meds',
        'medication',
        'clicks',
        'dischem',
        'dental',
        'optometrist',
        'discovery',
        'mediclinic',
        'netcare',
      ],
      isDefault: true,
      taxDeductibleByDefault: false,
    ),
    CategoryModel(
      categoryId: 'other',
      name: 'Other / Uncategorised',
      icon: '📋',
      color: '#B0B0B0',
      keywords: [],
      isDefault: true,
      taxDeductibleByDefault: false,
    ),
  ];
}
